<a href="https://colab.research.google.com/github/TanyaTejaswi/Walmart-Store-Clustering/blob/main/Walmart_Store_Clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
train = pd.read_csv("train.csv")
features = pd.read_csv("features.csv")
stores = pd.read_csv("stores.csv")

print("Train:", train.shape)
print("Features:", features.shape)
print("Stores:", stores.shape)

Train: (421570, 5)
Features: (8190, 12)
Stores: (45, 3)

In [ ]:
print("TRAIN")
display(train.head())

print("\nFEATURES")
display(features.head())

print("\nSTORES")
display(stores.head())

TRAIN

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

FEATURES

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

STORES

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

In [ ]:
print("TRAIN MISSING VALUES")
print(train.isnull().sum())

print("\nFEATURES MISSING VALUES")
print(features.isnull().sum())

print("\nSTORES MISSING VALUES")
print(stores.isnull().sum())

TRAIN MISSING VALUES
Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

FEATURES MISSING VALUES
Store              0
Date               0
Temperature        0
Fuel_Price         0
MarkDown1       4158
MarkDown2       5269
MarkDown3       4577
MarkDown4       4726
MarkDown5       4140
CPI              585
Unemployment     585
IsHoliday          0
dtype: int64

STORES MISSING VALUES
Store    0
Type     0
Size     0
dtype: int64

In [ ]:
print("TRAIN DATA TYPES")
print(train.dtypes)

print("\nFEATURES DATA TYPES")
print(features.dtypes)

print("\nSTORES DATA TYPES")
print(stores.dtypes)

print("\nDUPLICATES")
print("Train:", train.duplicated().sum())
print("Features:", features.duplicated().sum())
print("Stores:", stores.duplicated().sum())

TRAIN DATA TYPES
Store             int64
Dept              int64
Date             object
Weekly_Sales    float64
IsHoliday          bool
dtype: object

FEATURES DATA TYPES
Store             int64
Date             object
Temperature     float64
Fuel_Price      float64
MarkDown1       float64
MarkDown2       float64
MarkDown3       float64
MarkDown4       float64
MarkDown5       float64
CPI             float64
Unemployment    float64
IsHoliday          bool
dtype: object

STORES DATA TYPES
Store     int64
Type     object
Size      int64
dtype: object

DUPLICATES
Train: 0
Features: 0
Stores: 0

In [ ]:
train["Date"] = pd.to_datetime(train["Date"])
features["Date"] = pd.to_datetime(features["Date"])

print(train["Date"].dtype)
print(features["Date"].dtype)

datetime64[ns]
datetime64[ns]

In [ ]:
merged = pd.merge(
    train,
    features,
    on=["Store", "Date"],
    how="left"
)

print("Merged shape:", merged.shape)
print(merged.head())

Merged shape: (421570, 15)
   Store  Dept       Date  Weekly_Sales  IsHoliday_x  Temperature  Fuel_Price  \
0      1     1 2010-02-05      24924.50        False        42.31       2.572
1      1     1 2010-02-12      46039.49         True        38.51       2.548
2      1     1 2010-02-19      41595.55        False        39.93       2.514
3      1     1 2010-02-26      19403.54        False        46.63       2.561
4      1     1 2010-03-05      21827.90        False        46.50       2.625

   MarkDown1  MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  \
0        NaN        NaN        NaN        NaN        NaN  211.096358
1        NaN        NaN        NaN        NaN        NaN  211.242170
2        NaN        NaN        NaN        NaN        NaN  211.289143
3        NaN        NaN        NaN        NaN        NaN  211.319643
4        NaN        NaN        NaN        NaN        NaN  211.350143

   Unemployment  IsHoliday_y
0         8.106        False
1         8.106         True
2         8.106        False
3         8.106        False
4         8.106        False

In [ ]:
merged = merged.drop(columns=["IsHoliday_y"])
merged = merged.rename(columns={"IsHoliday_x": "IsHoliday"})

print(merged.columns.tolist())
print("Shape:", merged.shape)

['Store', 'Dept', 'Date', 'Weekly_Sales', 'IsHoliday', 'Temperature', 'Fuel_Price', 'MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5', 'CPI', 'Unemployment']
Shape: (421570, 14)

In [ ]:
merged = pd.merge(
    merged,
    stores,
    on="Store",
    how="left"
)

print("Shape:", merged.shape)
print(merged.head())

Shape: (421570, 16)
   Store  Dept       Date  Weekly_Sales  IsHoliday  Temperature  Fuel_Price  \
0      1     1 2010-02-05      24924.50      False        42.31       2.572
1      1     1 2010-02-12      46039.49       True        38.51       2.548
2      1     1 2010-02-19      41595.55      False        39.93       2.514
3      1     1 2010-02-26      19403.54      False        46.63       2.561
4      1     1 2010-03-05      21827.90      False        46.50       2.625

   MarkDown1  MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  \
0        NaN        NaN        NaN        NaN        NaN  211.096358
1        NaN        NaN        NaN        NaN        NaN  211.242170
2        NaN        NaN        NaN        NaN        NaN  211.289143
3        NaN        NaN        NaN        NaN        NaN  211.319643
4        NaN        NaN        NaN        NaN        NaN  211.350143

   Unemployment Type    Size
0         8.106    A  151315
1         8.106    A  151315
2         8.106    A  151315
3         8.106    A  151315
4         8.106    A  151315

In [ ]:
print("Number of stores:", merged["Store"].nunique())
print("Number of departments:", merged["Dept"].nunique())
print("Date range:", merged["Date"].min(), "to", merged["Date"].max())

print("\nStore types:")
print(merged["Type"].value_counts())

Number of stores: 45
Number of departments: 81
Date range: 2010-02-05 00:00:00 to 2012-10-26 00:00:00

Store types:
Type
A    215478
B    163495
C     42597
Name: count, dtype: int64

In [ ]:
print("Missing CPI rows:", merged["CPI"].isna().sum())
print("Missing Unemployment rows:", merged["Unemployment"].isna().sum())

print("\nDates with missing CPI:")
print(merged.loc[merged["CPI"].isna(), "Date"].unique())

print("\nDates with missing Unemployment:")
print(merged.loc[merged["Unemployment"].isna(), "Date"].unique())

Missing CPI rows: 0
Missing Unemployment rows: 0

Dates with missing CPI:
<DatetimeArray>
[]
Length: 0, dtype: datetime64[ns]

Dates with missing Unemployment:
<DatetimeArray>
[]
Length: 0, dtype: datetime64[ns]

In [ ]:
markdown_cols = [
    "MarkDown1",
    "MarkDown2",
    "MarkDown3",
    "MarkDown4",
    "MarkDown5"
]

merged[markdown_cols] = merged[markdown_cols].fillna(0)

print("Remaining missing values in Markdown columns:")
print(merged[markdown_cols].isnull().sum())

Remaining missing values in Markdown columns:
MarkDown1    0
MarkDown2    0
MarkDown3    0
MarkDown4    0
MarkDown5    0
dtype: int64

In [ ]:
print("Weekly Sales Statistics:")
print(merged["Weekly_Sales"].describe())

Weekly Sales Statistics:
count    421570.000000
mean      15981.258123
std       22711.183519
min       -4988.940000
25%        2079.650000
50%        7612.030000
75%       20205.852500
max      693099.360000
Name: Weekly_Sales, dtype: float64

In [ ]:
store_features = merged.groupby("Store").agg(
    Avg_Weekly_Sales=("Weekly_Sales", "mean"),
    Sales_Std=("Weekly_Sales", "std"),
    Total_Sales=("Weekly_Sales", "sum"),
    Min_Sales=("Weekly_Sales", "min"),
    Max_Sales=("Weekly_Sales", "max"),
    Num_Departments=("Dept", "nunique")
).reset_index()

print("Shape:", store_features.shape)
display(store_features.head())

Shape: (45, 7)

,Store,Avg_Weekly_Sales,Sales_Std,Total_Sales,Min_Sales,Max_Sales,Num_Departments
0,1,21710.543621,27748.945511,2.224028e+08,-863.00,203670.47,77
1,2,26898.070031,33077.612059,2.753824e+08,-1098.00,285353.53,78
2,3,6373.033983,14251.034807,5.758674e+07,-1008.96,155897.94,72
3,4,29161.210415,34583.677814,2.995440e+08,-898.00,385051.04,78
4,5,5053.415813,8068.221050,4.547569e+07,-101.26,93517.72,72

In [ ]:
store_info = stores.copy()

store_features = pd.merge(
    store_features,
    store_info,
    on="Store",
    how="left"
)

print("Shape:", store_features.shape)
display(store_features.head())

Shape: (45, 9)

,Store,Avg_Weekly_Sales,Sales_Std,Total_Sales,Min_Sales,Max_Sales,Num_Departments,Type,Size
0,1,21710.543621,27748.945511,2.224028e+08,-863.00,203670.47,77,A,151315
1,2,26898.070031,33077.612059,2.753824e+08,-1098.00,285353.53,78,A,202307
2,3,6373.033983,14251.034807,5.758674e+07,-1008.96,155897.94,72,B,37392
3,4,29161.210415,34583.677814,2.995440e+08,-898.00,385051.04,78,A,205863
4,5,5053.415813,8068.221050,4.547569e+07,-101.26,93517.72,72,B,34875

In [ ]:
economic_features = merged.groupby("Store")[[
    "Temperature",
    "Fuel_Price",
    "CPI",
    "Unemployment"
]].mean().reset_index()

economic_features = economic_features.rename(columns={
    "Temperature": "Avg_Temperature",
    "Fuel_Price": "Avg_Fuel_Price",
    "CPI": "Avg_CPI",
    "Unemployment": "Avg_Unemployment"
})

store_features = store_features.merge(
    economic_features,
    on="Store",
    how="left"
)

print("Shape:", store_features.shape)

Shape: (45, 13)

In [ ]:
markdown_features = merged.groupby("Store").agg(
    Avg_MarkDown1=("MarkDown1", "mean"),
    Avg_MarkDown2=("MarkDown2", "mean"),
    Avg_MarkDown3=("MarkDown3", "mean"),
    Avg_MarkDown4=("MarkDown4", "mean"),
    Avg_MarkDown5=("MarkDown5", "mean")
).reset_index()

store_features = store_features.merge(
    markdown_features,
    on="Store",
    how="left"
)

print("Shape:", store_features.shape)

Shape: (45, 18)

In [ ]:
holiday_features = merged.groupby(
    ["Store", "IsHoliday"]
)["Weekly_Sales"].mean().unstack(fill_value=0).reset_index()

holiday_features = holiday_features.rename(columns={
    False: "Avg_NonHoliday_Sales",
    True: "Avg_Holiday_Sales"
})

holiday_features["Holiday_Sales_Ratio"] = (
    holiday_features["Avg_Holiday_Sales"] /
    holiday_features["Avg_NonHoliday_Sales"]
)

store_features = store_features.merge(
    holiday_features,
    on="Store",
    how="left"
)

print("Shape:", store_features.shape)
display(store_features.head())

Shape: (45, 21)

,Store,Avg_Weekly_Sales,Sales_Std,Total_Sales,Min_Sales,Max_Sales,Num_Departments,Type,Size,Avg_Temperature,...,Avg_CPI,Avg_Unemployment,Avg_MarkDown1,Avg_MarkDown2,Avg_MarkDown3,Avg_MarkDown4,Avg_MarkDown5,Avg_NonHoliday_Sales,Avg_Holiday_Sales,Holiday_Sales_Ratio
0,1,21710.543621,27748.945511,2.224028e+08,-863.00,203670.47,77,A,151315,68.224463,...,215.995525,7.610918,2886.877467,873.291894,436.207316,1340.570529,1794.852645,21609.634733,23039.386667,1.066163
1,2,26898.070031,33077.612059,2.753824e+08,-1098.00,285353.53,78,A,202307,68.105435,...,215.651869,7.623279,3815.003642,1571.495877,608.139075,1702.223652,2342.706654,26753.864227,28798.710526,1.076432
2,3,6373.033983,14251.034807,5.758674e+07,-1008.96,155897.94,72,B,37392,71.298627,...,219.402843,7.175602,1104.843804,294.276057,288.622421,317.644571,455.513285,6332.098604,6916.446288,1.092283
3,4,29161.210415,34583.677814,2.995440e+08,-898.00,385051.04,78,A,205863,62.176867,...,128.680070,5.965849,3352.829782,1381.076520,686.803667,1839.689313,2438.110453,29032.260570,30854.231417,1.062757
4,5,5053.415813,8068.221050,4.547569e+07,-101.26,93517.72,72,B,34875,69.203619,...,216.576516,6.296549,1079.143440,300.162839,235.176435,395.045179,915.256248,5010.249172,5617.212609,1.121144

In [ ]:
numeric_features = store_features.select_dtypes(include=["number"])

correlation = numeric_features.corr()

display(correlation.round(2))

,Store,Avg_Weekly_Sales,Sales_Std,Total_Sales,Min_Sales,Max_Sales,Num_Departments,Size,Avg_Temperature,Avg_Fuel_Price,Avg_CPI,Avg_Unemployment,Avg_MarkDown1,Avg_MarkDown2,Avg_MarkDown3,Avg_MarkDown4,Avg_MarkDown5,Avg_NonHoliday_Sales,Avg_Holiday_Sales,Holiday_Sales_Ratio
Store,1.00,-0.30,-0.25,-0.35,-0.02,-0.24,-0.51,-0.24,-0.04,0.20,-0.21,0.24,-0.35,-0.38,-0.46,-0.32,-0.11,-0.30,-0.32,-0.50
Avg_Weekly_Sales,-0.30,1.00,0.97,0.99,-0.12,0.68,0.55,0.81,-0.02,0.05,-0.06,-0.09,0.75,0.85,0.80,0.79,0.61,1.00,1.00,0.07
Sales_Std,-0.25,0.97,1.00,0.95,-0.10,0.62,0.42,0.73,0.04,0.04,-0.04,-0.06,0.66,0.76,0.71,0.70,0.55,0.97,0.97,-0.01
Total_Sales,-0.35,0.99,0.95,1.00,-0.13,0.70,0.64,0.85,-0.08,0.05,-0.08,-0.11,0.80,0.89,0.84,0.84,0.62,0.99,0.99,0.15
Min_Sales,-0.02,-0.12,-0.10,-0.13,1.00,-0.38,-0.17,-0.15,-0.07,-0.16,0.11,-0.34,-0.28,-0.08,-0.12,-0.24,-0.13,-0.11,-0.15,-0.39
Max_Sales,-0.24,0.68,0.62,0.70,-0.38,1.00,0.58,0.52,-0.11,0.32,-0.26,0.11,0.78,0.74,0.80,0.76,0.48,0.68,0.71,0.52
Num_Departments,-0.51,0.55,0.42,0.64,-0.17,0.58,1.00,0.77,-0.45,0.03,-0.08,-0.18,0.84,0.78,0.80,0.79,0.50,0.55,0.58,0.62
Size,-0.24,0.81,0.73,0.85,-0.15,0.52,0.77,1.00,-0.18,0.01,-0.01,-0.09,0.83,0.81,0.73,0.82,0.67,0.81,0.81,0.20
Avg_Temperature,-0.04,-0.02,0.04,-0.08,-0.07,-0.11,-0.45,-0.18,1.00,-0.08,0.32,0.27,-0.27,-0.27,-0.29,-0.24,0.07,-0.02,-0.03,-0.23
Avg_Fuel_Price,0.20,0.05,0.04,0.05,-0.16,0.32,0.03,0.01,-0.08,1.00,-0.72,0.47,0.19,0.17,0.16,0.21,-0.10,0.05,0.07,0.13
Avg_CPI,-0.21,-0.06,-0.04,-0.08,0.11,-0.26,-0.08,-0.01,0.32,-0.72,1.00,-0.30,-0.13,-0.14,-0.19,-0.16,0.12,-0.06,-0.08,-0.14
Avg_Unemployment,0.24,-0.09,-0.06,-0.11,-0.34,0.11,-0.18,-0.09,0.27,0.47,-0.30,1.00,0.03,-0.10,-0.18,-0.01,-0.02,-0.09,-0.07,0.13
Avg_MarkDown1,-0.35,0.75,0.66,0.80,-0.28,0.78,0.84,0.83,-0.27,0.19,-0.13,0.03,1.00,0.91,0.82,0.97,0.62,0.75,0.78,0.49
Avg_MarkDown2,-0.38,0.85,0.76,0.89,-0.08,0.74,0.78,0.81,-0.27,0.17,-0.14,-0.10,0.91,1.00,0.91,0.94,0.54,0.85,0.86,0.29
Avg_MarkDown3,-0.46,0.80,0.71,0.84,-0.12,0.80,0.80,0.73,-0.29,0.16,-0.19,-0.18,0.82,0.91,1.00,0.84,0.54,0.80,0.82,0.43
Avg_MarkDown4,-0.32,0.79,0.70,0.84,-0.24,0.76,0.79,0.82,-0.24,0.21,-0.16,-0.01,0.97,0.94,0.84,1.00,0.58,0.79,0.81,0.39
Avg_MarkDown5,-0.11,0.61,0.55,0.62,-0.13,0.48,0.50,0.67,0.07,-0.10,0.12,-0.02,0.62,0.54,0.54,0.58,1.00,0.60,0.61,0.23
Avg_NonHoliday_Sales,-0.30,1.00,0.97,0.99,-0.11,0.68,0.55,0.81,-0.02,0.05,-0.06,-0.09,0.75,0.85,0.80,0.79,0.60,1.00,1.00,0.07
Avg_Holiday_Sales,-0.32,1.00,0.97,0.99,-0.15,0.71,0.58,0.81,-0.03,0.07,-0.08,-0.07,0.78,0.86,0.82,0.81,0.61,1.00,1.00,0.14
Holiday_Sales_Ratio,-0.50,0.07,-0.01,0.15,-0.39,0.52,0.62,0.20,-0.23,0.13,-0.14,0.13,0.49,0.29,0.43,0.39,0.23,0.07,0.14,1.00

In [ ]:
store_features["Avg_Total_MarkDown"] = (
    store_features["Avg_MarkDown1"] +
    store_features["Avg_MarkDown2"] +
    store_features["Avg_MarkDown3"] +
    store_features["Avg_MarkDown4"] +
    store_features["Avg_MarkDown5"]
)

print(store_features[[
    "Store",
    "Avg_Total_MarkDown"
]].head())

   Store  Avg_Total_MarkDown
0      1         7331.799851
1      2        10039.568900
2      3         2460.900137
3      4         9698.509734
4      5         2924.784143

In [ ]:
cluster_features = store_features[[
    "Store",
    "Avg_Weekly_Sales",
    "Sales_Std",
    "Size",
    "Num_Departments",
    "Avg_Total_MarkDown",
    "Avg_Temperature",
    "Avg_Fuel_Price",
    "Avg_CPI",
    "Avg_Unemployment",
    "Holiday_Sales_Ratio",
    "Type"
]].copy()

print("Shape:", cluster_features.shape)
display(cluster_features.head())

Shape: (45, 12)

,Store,Avg_Weekly_Sales,Sales_Std,Size,Num_Departments,Avg_Total_MarkDown,Avg_Temperature,Avg_Fuel_Price,Avg_CPI,Avg_Unemployment,Holiday_Sales_Ratio,Type
0,1,21710.543621,27748.945511,151315,77,7331.799851,68.224463,3.218811,215.995525,7.610918,1.066163,A
1,2,26898.070031,33077.612059,202307,78,10039.568900,68.105435,3.219898,215.651869,7.623279,1.076432,A
2,3,6373.033983,14251.034807,37392,72,2460.900137,71.298627,3.219112,219.402843,7.175602,1.092283,B
3,4,29161.210415,34583.677814,205863,78,9698.509734,62.176867,3.216237,128.680070,5.965849,1.062757,A
4,5,5053.415813,8068.221050,34875,72,2924.784143,69.203619,3.220912,216.576516,6.296549,1.121144,B

In [ ]:
cluster_encoded = pd.get_dummies(
    cluster_features,
    columns=["Type"],
    dtype=int
)

print("Shape:", cluster_encoded.shape)
display(cluster_encoded.head())

Shape: (45, 14)

,Store,Avg_Weekly_Sales,Sales_Std,Size,Num_Departments,Avg_Total_MarkDown,Avg_Temperature,Avg_Fuel_Price,Avg_CPI,Avg_Unemployment,Holiday_Sales_Ratio,Type_A,Type_B,Type_C
0,1,21710.543621,27748.945511,151315,77,7331.799851,68.224463,3.218811,215.995525,7.610918,1.066163,1,0,0
1,2,26898.070031,33077.612059,202307,78,10039.568900,68.105435,3.219898,215.651869,7.623279,1.076432,1,0,0
2,3,6373.033983,14251.034807,37392,72,2460.900137,71.298627,3.219112,219.402843,7.175602,1.092283,0,1,0
3,4,29161.210415,34583.677814,205863,78,9698.509734,62.176867,3.216237,128.680070,5.965849,1.062757,1,0,0
4,5,5053.415813,8068.221050,34875,72,2924.784143,69.203619,3.220912,216.576516,6.296549,1.121144,0,1,0

In [ ]:
store_ids = cluster_encoded["Store"]

X = cluster_encoded.drop(columns=["Store"])

print("Clustering features shape:", X.shape)
print(X.columns.tolist())

Clustering features shape: (45, 13)
['Avg_Weekly_Sales', 'Sales_Std', 'Size', 'Num_Departments', 'Avg_Total_MarkDown', 'Avg_Temperature', 'Avg_Fuel_Price', 'Avg_CPI', 'Avg_Unemployment', 'Holiday_Sales_Ratio', 'Type_A', 'Type_B', 'Type_C']

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Scaled shape:", X_scaled.shape)
print("Mean of first 5 features:", X_scaled[:, :5].mean(axis=0))
print("Std of first 5 features:", X_scaled[:, :5].std(axis=0))

Scaled shape: (45, 13)
Mean of first 5 features: [ 5.69914486e-16  2.31913254e-16 -1.01153653e-16 -6.33578838e-16
 -1.59748757e-16]
Std of first 5 features: [1. 1. 1. 1. 1.]

In [ ]:
from sklearn.cluster import KMeans

inertias = []

for k in range(2, 9):
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    kmeans.fit(X_scaled)
    inertias.append(kmeans.inertia_)

for k, inertia in zip(range(2, 9), inertias):
    print(f"K = {k}, Inertia = {inertia:.2f}")

K = 2, Inertia = 409.39
K = 3, Inertia = 275.00
K = 4, Inertia = 239.03
K = 5, Inertia = 206.53
K = 6, Inertia = 187.71
K = 7, Inertia = 166.69
K = 8, Inertia = 150.05

In [ ]:
from sklearn.metrics import silhouette_score

silhouette_scores = []

for k in range(2, 9):
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(X_scaled)
    score = silhouette_score(X_scaled, labels)
    silhouette_scores.append(score)

for k, score in zip(range(2, 9), silhouette_scores):
    print(f"K = {k}, Silhouette Score = {score:.4f}")

K = 2, Silhouette Score = 0.2721
K = 3, Silhouette Score = 0.3405
K = 4, Silhouette Score = 0.3308
K = 5, Silhouette Score = 0.2687
K = 6, Silhouette Score = 0.2494
K = 7, Silhouette Score = 0.2648
K = 8, Silhouette Score = 0.2478

In [ ]:
kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

cluster_labels = kmeans.fit_predict(X_scaled)

cluster_features["Cluster"] = cluster_labels

print("Cluster counts:")
print(cluster_features["Cluster"].value_counts().sort_index())

Cluster counts:
Cluster
0    17
1    20
2     8
Name: count, dtype: int64

In [ ]:
cluster_analysis = cluster_features.copy()

cluster_summary = cluster_analysis.groupby("Cluster").agg(
    Avg_Weekly_Sales=("Avg_Weekly_Sales", "mean"),
    Sales_Std=("Sales_Std", "mean"),
    Avg_Store_Size=("Size", "mean"),
    Avg_Departments=("Num_Departments", "mean"),
    Avg_MarkDown=("Avg_Total_MarkDown", "mean"),
    Avg_Temperature=("Avg_Temperature", "mean"),
    Avg_Fuel_Price=("Avg_Fuel_Price", "mean"),
    Avg_CPI=("Avg_CPI", "mean"),
    Avg_Unemployment=("Avg_Unemployment", "mean"),
    Avg_Holiday_Ratio=("Holiday_Sales_Ratio", "mean")
).round(2)

print("Cluster Summary:")
display(cluster_summary)

Cluster Summary:

,Avg_Weekly_Sales,Sales_Std,Avg_Store_Size,Avg_Departments,Avg_MarkDown,Avg_Temperature,Avg_Fuel_Price,Avg_CPI,Avg_Unemployment,Avg_Holiday_Ratio
Cluster,,,,,,,,,,
0,12087.38,15277.55,101190.71,75.65,6170.19,57.70,3.38,168.15,7.92,1.10
1,20873.22,25532.07,190992.50,77.25,8669.56,59.68,3.34,174.76,7.77,1.07
2,8970.54,14380.20,40356.25,62.50,709.71,69.18,3.37,171.00,8.74,1.00

In [ ]:
type_distribution = pd.crosstab(
    cluster_features["Cluster"],
    cluster_features["Type"]
)

print("Store Type Distribution by Cluster:")
display(type_distribution)

Store Type Distribution by Cluster:

Type      A   B  C
Cluster
0         0  17  0
1        20   0  0
2         2   0  6

In [ ]:
X_no_type = cluster_features.drop(
    columns=["Store", "Type"]
)

print("Features without Type:", X_no_type.shape)
print(X_no_type.columns.tolist())

Features without Type: (45, 11)
['Avg_Weekly_Sales', 'Sales_Std', 'Size', 'Num_Departments', 'Avg_Total_MarkDown', 'Avg_Temperature', 'Avg_Fuel_Price', 'Avg_CPI', 'Avg_Unemployment', 'Holiday_Sales_Ratio', 'Cluster']

In [ ]:
X_no_type = cluster_features.drop(
    columns=["Store", "Type", "Cluster"]
)

print("Features without Type:", X_no_type.shape)
print(X_no_type.columns.tolist())

Features without Type: (45, 10)
['Avg_Weekly_Sales', 'Sales_Std', 'Size', 'Num_Departments', 'Avg_Total_MarkDown', 'Avg_Temperature', 'Avg_Fuel_Price', 'Avg_CPI', 'Avg_Unemployment', 'Holiday_Sales_Ratio']

In [ ]:
scaler_no_type = StandardScaler()

X_no_type_scaled = scaler_no_type.fit_transform(X_no_type)

print("Scaled shape:", X_no_type_scaled.shape)
print("Mean:", X_no_type_scaled.mean(axis=0).round(4))
print("Std:", X_no_type_scaled.std(axis=0).round(4))

Scaled shape: (45, 10)
Mean: [ 0.  0. -0. -0. -0. -0. -0.  0. -0. -0.]
Std: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

In [ ]:
silhouette_no_type = []

for k in range(2, 9):
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(X_no_type_scaled)
    score = silhouette_score(X_no_type_scaled, labels)
    silhouette_no_type.append(score)

for k, score in zip(range(2, 9), silhouette_no_type):
    print(f"K = {k}, Silhouette Score = {score:.4f}")

K = 2, Silhouette Score = 0.3125
K = 3, Silhouette Score = 0.2611
K = 4, Silhouette Score = 0.2597
K = 5, Silhouette Score = 0.2716
K = 6, Silhouette Score = 0.2849
K = 7, Silhouette Score = 0.2965
K = 8, Silhouette Score = 0.2906

In [ ]:
final_kmeans = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=10
)

final_labels = final_kmeans.fit_predict(X_no_type_scaled)

final_clusters = cluster_features[[
    "Store",
    "Type",
    "Avg_Weekly_Sales",
    "Sales_Std",
    "Size",
    "Num_Departments",
    "Avg_Total_MarkDown",
    "Avg_Temperature",
    "Avg_Fuel_Price",
    "Avg_CPI",
    "Avg_Unemployment",
    "Holiday_Sales_Ratio"
]].copy()

final_clusters["Cluster"] = final_labels

print("Final cluster counts:")
print(final_clusters["Cluster"].value_counts().sort_index())

Final cluster counts:
Cluster
0    33
1    12
Name: count, dtype: int64

In [ ]:
final_summary = final_clusters.groupby("Cluster").agg(
    Avg_Weekly_Sales=("Avg_Weekly_Sales", "mean"),
    Sales_Std=("Sales_Std", "mean"),
    Avg_Store_Size=("Size", "mean"),
    Avg_Departments=("Num_Departments", "mean"),
    Avg_MarkDown=("Avg_Total_MarkDown", "mean"),
    Avg_Temperature=("Avg_Temperature", "mean"),
    Avg_Fuel_Price=("Avg_Fuel_Price", "mean"),
    Avg_CPI=("Avg_CPI", "mean"),
    Avg_Unemployment=("Avg_Unemployment", "mean"),
    Avg_Holiday_Ratio=("Holiday_Sales_Ratio", "mean")
).round(2)

print("Final Cluster Summary:")
display(final_summary)

Final Cluster Summary:

,Avg_Weekly_Sales,Sales_Std,Avg_Store_Size,Avg_Departments,Avg_MarkDown,Avg_Temperature,Avg_Fuel_Price,Avg_CPI,Avg_Unemployment,Avg_Holiday_Ratio
Cluster,,,,,,,,,,
0,18026.89,21972.80,160145.30,76.91,8058.91,58.22,3.37,166.80,8.00,1.08
1,8318.91,13358.23,48178.92,66.08,1501.53,67.22,3.32,184.78,7.99,1.03

In [ ]:
final_type_distribution = pd.crosstab(
    final_clusters["Cluster"],
    final_clusters["Type"]
)

print("Store Type Distribution in Final Clusters:")
display(final_type_distribution)

Store Type Distribution in Final Clusters:

Type      A   B  C
Cluster
0        20  13  0
1         2   4  6